[manifest]
version = "1.2"
dump_lua = true
priority = 0


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = """    initSteamodded()"""
position = "after"
payload = """AKYRS.add_colours(G.C)
AKYRS.add_formatting_colours(G.ARGS.LOC_COLOURS)"""
overwrite = true
match_indent = true

