[manifest]
version = "1.2"
dump_lua = true
priority = -11212


[[patches]]
[patches.pattern]
target = '''game.lua'''
pattern = """
shader = 'splash',
"""
position = "at"
payload = '''
shader = 'akyrs_aiko_splash',
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''game.lua'''
pattern = """            {name = 'colour_1', ref_table = G.C, ref_value = 'RED'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'BLUE'},
"""
position = "at"
payload = '''            {name = 'colour_1', ref_table = G.C, ref_value = 'AKYRS_AIKOYORI_BOW'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'AKYRS_AIKOYORI_HAIR'},
'''
match_indent = true